version: "3.2"
services:
  springapp:
    image: dockerhandson/spring-boot-mongo:1
    ports:
    - 8080:8080
    networks:
    - springappnetwork
    environment:
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    - MONGO_DB_HOSTNAME=mongo
    container_name: springappcontainer

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
    - mongodbvol:/data/db
    networks:
    - springappnetwork

volumes:
  mongodbvol:
    driver: local
networks:
  springappnetwork:
    driver: bridge
